runtime: python39
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto


# Add system packages
system_packages:
  - name: libgl1-mesa-glx
  - name: libglib2.0-dev
